## 1、如何改变一个Promise实例的状态

1. 执行`resolve(value)`：如果当前是`pending`就会变为`fulfilled`

2. 执行`reject(reason)`：如果当前是`pending`就会变为`rejected`

3. ==执行器函数(`executor`)抛出异常==：如果当前是`pending`就会变为`rejected`

   1. 引擎抛异常

      - 抛出异常后，Promise实例的状态变为`rejected`并且会停止执行代码。

      - ``` js
              const p = new Promise((resolve, reject) => {
                // 输出一个未定义的变量
                console.log(a);
                resolve(100);
              });
          
              p.then(
                (value) => {
                  console.log("成功了", value);
                },
                (reason) => {
                  console.log("失败了", reason);
                }
              );
        ```

   2. 自己主动编码抛异常
   
      - 抛出异常后，Promise实例的状态变为`rejected`并且会停止执行代码。
   
      - ``` js
              const p = new Promise((resolve, reject) => {
                // 主动抛出异常
                throw new Error(99);
                resolve(100);
              });
          
              p.then(
                (value) => {
                  console.log("成功了", value);
                },
                (reason) => {
                  console.log("失败了", reason);
                }
              );
        ```
   
   3. ==在抛出异常前，已经`resolve(xx)`改变实例状态了，同步代码在抛出异常后==
   
      - 实例状态变为`fulfilled`，再抛出异常，不会改变Promise实例的状态，但会停止执行后面的代码
   
      - ``` js
              const p = new Promise((resolve, reject) => {
                // 改变状态后抛出异常
                resolve(100);
                throw new Error(99);
                console.log(1)
            });
            
              p.then(
                (value) => {
                  console.log("成功了", value);
                },
                (reason) => {
                  console.log("失败了", reason);
                }
            );
          
          // 输出：'成功了'100
          ```
          
   
   4. ==在抛出异常前，已经`resolve(xx)`改变实例状态了，同步代码在抛出异常前==
   
      - 实例状态变为`fulfilled`，再抛出异常，不会改变Promise实例的状态，抛出异常会终止代码的执行，但在抛出异常前的同步代码仍然会正常执行
      
      - ``` js
            const p = new Promise((resolve, reject) => {
              // 改变状态后抛出异常
              resolve(100);
              console.log(1)
              throw new Error(99);
          });
          
            p.then(
              (value) => {
                console.log("成功了", value);
              },
              (reason) => {
                console.log("失败了", reason);
              }
          );
        // 输出 1 
        // "成功了"100  (异步回调)        
        ```
      
      - 

## 2、改变Promise实例状态与指定回调函数的顺序

- 顺序==都有可能==。正常情况下是先指定回调再改变状态，但也可以先改变状态再指定回调

- 如何==先改变状态，再指定回调==？

  - 延迟一会儿再调用`then()`

- Promise实例==什么时候才能得到数据==？

  - 如果先指定的回调，==回调函数会被存在实例对象的属性中==。那么当状态发生改变时，回调函数就会被调用，从而得到数据
  - 如果先改变的状态，==抛出来的数据会被存到实例对象的属性中==。那么==当指定了回调函数时，会立马调用，不会再将回调函数存储，从而得到数据==

- 情况讨论

  1. 先指定回调再改变状态（最常见）

     1. ``` js
              const p = new Promise((resolve, reject) => {
                setTimeout(() => {
                  resolve(100);
                }, 2000);
              });
           
              p.then(
                (value) => {
                  console.log("成功了", value);
                },
                (reason) => {
                  console.log("失败了", reason);
                }
              );
           
        ```

     2. `执行new Promise()`，运行同步的回调函数`executor`，在`executor`内部运行`setTimeout()`开启定时器2秒钟后将异步回调压入异步队列中。继续执行同步代码`p.then()`，定义好了实例对象状态为成功和失败的异步回调函数，放入实例对象的属性上。2秒钟后`Promise`实例对象状态变为成功，执行成功的回调函数。

     3. ![image-20220808110107797](C:\Users\zayn\AppData\Roaming\Typora\typora-user-images\image-20220808110107797.png)

  2. 先改变状态再指定回调

     1. ``` js
              const p = new Promise((resolve, reject) => {
                resolve(100);
              });
           
              setTimeout(() => {
                p.then(
                  (value) => {
                    console.log("成功了", value);
                  },
                  (reason) => {
                    console.log("失败了", reason);
                  }
                );
              }, 2000);
        ```

     2. `执行new Promise()`，运行同步的回调函数`executor`，在`executor`内部运行`resolve(100)`改变实例状态，抛出来的100会被保存在实例的属性上。继续执行同步代码`setTimeout()`开启定时器2秒钟后将异步回调压入异步队列中。2秒钟后定义好了实例对象状态为成功和失败的异步回调函数，立马执行

     3. ![image-20220808111106628](C:\Users\zayn\AppData\Roaming\Typora\typora-user-images\image-20220808111106628.png)

## 3、==then的链式调用==

Promise实例.then()返回的是一个==【新的`Promise`实例】==，它的值和状态由什么决定？

1. 简单表达：==由`then()`所指定的回调函数执行的结果决定==
2. 详细表达：
   1. 如果`then`所指定的==回调返回的是非Promise值a==
      - 那么==【新的`Promise`实例】==状态为：成功(fulfilled)，成功的value为a
      
      - 例子1，未设置返回值
      
        - ``` js
          // 1. 执行new Promise(executor)，返回一个Promise实例对象，用变量p接收。executor是同步回调函数，会立马执行 
          const p = new Promise((resolve, reject) => {
              // 1.1 执行setTimeout()，开启定时器，1s钟后将异步回调函数压入异步队列
          	setTimeout(()=>{
          		resolve('a')
                  console.log(1)
              }, 1000)
          });
          
          // 2. 执行p.then()，返回一个Promise实例，用变量x接收。指定好了p实例成功和失败状态的回调函数，但目前还未执行
          const x = p.then(
          	(value) => {
          		console.log("p成功了", value);
          	},
          	(reason) => {
          		console.log("p失败了", reason);
          	}
          );
          
          // 3. 执行x.then()，返回一个Promise实例，并未接收。制定好了x实例成功和失败状态的回调函数，但目前还未执行
          x.then(
          	(value) => {
          		console.log("x成功了", value);
          	},
          	(reason) => {
          		console.log("x失败了", reason);
          	}
          );
          
          // 4. 同步代码执行完毕后，执行异步队列里的任务，定时器的异步回调，
          	//4.1 改变了实例p的状态为成功，且value为'a'。然后将实例p的成功回调函数压入异步队列中。
          	//4.2 接着执行console.log(1)，打印出1(得先把当前任务执行完毕，再去考虑其他任务)
          
          // 5. 执行完毕后，从异步队列里拿出任务，实例p的成功回调函数
          	//5.1 执行console.log("p成功了", value)，打印 "p成功了"a
          	//5.2 虽然程序员没有写return xxx，但实际上js引擎补充了 return undefined
          	//5.3 返回的是一个非Promise值，所以x的状态变为fulfiilled，value为返回的值undefined。将实例x成功的回调函数压入异步队列中
          
          // 6. 执行完毕后，从异步队列里拿出任务，实例x的成功回调函数
          	// 6.1 执行console.log("x成功了", value); 打印 "x成功了"undefined
          ```
      
      - 例子2，设置普通返回值
      
        - ``` js
          // 1. 执行new Promise(executor)，返回一个Promise实例对象，用变量p接收。executor是同步回调函数，会立马执行 
          const p = new Promise((resolve, reject) => {
              // 1.1 执行setTimeout()，开启定时器，1s钟后将异步回调函数压入异步队列
          	setTimeout(()=>{
          		resolve('a')
                  console.log(1)
              }, 1000)
          });
          
          // 2. 执行p.then()，返回一个Promise实例，用变量x接收。指定好了p实例成功和失败状态的回调函数，但目前还未执行
          const x = p.then(
          	(value) => {
          		console.log("p成功了", value)
                  return 900
          	},
          	(reason) => {
          		console.log("p失败了", reason)
          	}
          );
          
          // 3. 执行x.then()，返回一个Promise实例，并未接收。制定好了x实例成功和失败状态的回调函数，但目前还未执行
          x.then(
          	(value) => {
          		console.log("x成功了", value)
          	},
          	(reason) => {
          		console.log("x失败了", reason)
          	}
          );
          
          // 4. 同步代码执行完毕后，执行异步队列里的任务，定时器的异步回调，
          	//4.1 改变了实例p的状态为成功，且value为'a'。然后将实例p的成功回调函数压入异步队列中。
          	//4.2 接着执行console.log(1)，打印出1(得先把当前任务执行完毕，再去考虑其他任务)
          
          // 5. 执行完毕后，从异步队列里拿出任务，实例p的成功回调函数
          	//5.1 执行console.log("p成功了", value)，打印 "p成功了"a
          	//5.2 返回的是一个非Promise值，所以x的状态变为fulfiilled，value为返回的值900。将实例x成功的回调函数压入异步队列中
          
          // 6. 执行完毕后，从异步队列里拿出任务，实例x的成功回调函数
          	// 6.1 执行console.log("x成功了", value); 打印 "x成功了"900
          ```
      
        - 
   2. 如果`then`所指定的==回调返回的是一个`Promise`实例==
      - 那么==【新的`Promise`实例】==状态、值都==与该返回的Promise实例一致==
      
      - 示例一：返回的是成功状态Promise实例
      
        - ``` js
          // 1. 执行new Promise(executor)，返回一个Promise实例对象，用变量p接收。executor是同步回调函数，会立马执行 
          const p = new Promise((resolve, reject) => {
              // 1.1 执行setTimeout()，开启定时器，1s钟后将异步回调函数压入异步队列
          	setTimeout(()=>{
          		resolve('a')
                  console.log(1)
              }, 1000)
          });
          
          // 2. 执行p.then()，返回一个Promise实例，用变量x接收。指定好了p实例成功和失败状态的回调函数，但目前还未执行
          const x = p.then(
          	(value) => {
          		console.log("p成功了", value)
                  return Promise.resolve(100)
          	},
          	(reason) => {
          		console.log("p失败了", reason)
          	}
          );
          
          // 3. 执行x.then()，返回一个Promise实例，并未接收。制定好了x实例成功和失败状态的回调函数，但目前还未执行
          x.then(
          	(value) => {
          		console.log("x成功了", value)
          	},
          	(reason) => {
          		console.log("x失败了", reason)
          	}
          );
          
          // 4. 同步代码执行完毕后，执行异步队列里的任务，定时器的异步回调，
          	//4.1 改变了实例p的状态为成功，且value为'a'。然后将实例p的成功回调函数压入异步队列中。
          	//4.2 接着执行console.log(1)，打印出1(得先把当前任务执行完毕，再去考虑其他任务)
          
          // 5. 执行完毕后，从异步队列里拿出任务，实例p的成功回调函数
          	//5.1 执行console.log("p成功了", value)，打印 "p成功了"a
          	//5.2 返回的是一个Promise实例，该返回的Promise实例状态是成功的，且value是100。所以x的状态也变为成功的，且value是100。将x的成功状态对应的回调函数压入异步队列中。
          
          // 6. 执行完毕后，从异步队列里拿出任务，实例x的成功回调函数
          	// 6.1 执行console.log("x成功了", value); 打印 "x成功了"100
          ```
      
      - 示例二：p的状态为rejected
      
        - ``` js
          // 1. 执行new Promise(executor)，返回一个Promise实例对象，用变量p接收。executor是同步回调函数，会立马执行 
          const p = new Promise((resolve, reject) => {
              // 1.1 执行setTimeout()，开启定时器，1s钟后将异步回调函数压入异步队列
          	setTimeout(()=>{
          		reject('a')
                  console.log(1)
              }, 1000)
          });
          
          // 2. 执行p.then()，返回一个Promise实例，用变量x接收。指定好了p实例成功和失败状态的回调函数，但目前还未执行
          const x = p.then(
          	(value) => {
          		console.log("p成功了", value)
                  return Promise.reject(100)
          	},
          	(reason) => {
          		console.log("p失败了", reason)
          	}
          );
          
          // 3. 执行x.then()，返回一个Promise实例，并未接收。指定好了x实例成功和失败状态的回调函数，但目前还未执行
          x.then(
          	(value) => {
          		console.log("x成功了", value)
          	},
          	(reason) => {
          		console.log("x失败了", reason)
          	}
          );
          
          // 4. 同步代码执行完毕后，执行异步队列里的任务，定时器的异步回调，
          	//4.1 改变了实例p的状态为失败，且reason为'a'。然后将实例p的失败回调函数压入异步队列中。
          	//4.2 接着执行console.log(1)，打印出1(得先把当前任务执行完毕，再去考虑其他任务)
          
          // 5. 执行完毕后，从异步队列里拿出任务，实例p的失败回调函数
          	//5.1 执行console.log("p失败了", reason)，打印 "p失败了"a
          	//5.2 未设置返回值，默认返回undefined，是一个非Promise值。所以x的状态也变为成功的，且value是undefined。将x的成功状态对应的回调函数压入异步队列中。
          
          // 6. 执行完毕后，从异步队列里拿出任务，实例x的成功回调函数
          	// 6.1 执行console.log("x成功了", value); 打印 "x成功了"undefined
          ```
      
      - 示例三：then的链式调用
      
        - ``` js
          // 1. 执行new Promise(executor)，返回一个Promise实例对象，用变量p接收。executor是同步回调函数，会立马执行 
          const p = new Promise((resolve, reject) => {
              // 1.1 执行setTimeout()，开启定时器，1s钟后将异步回调函数压入异步队列
          	setTimeout(()=>{
          		resolve('a')
                  console.log(1)
              }, 1000)
          });
          
          // 2. 执行p.then()，返回一个Promise实例，没有接收，称为Promise实例1。指定好了p实例成功和失败状态的回调函数，但目前还未执行
          p.then(
          	(value) => {
          		console.log("p成功了1", value)
                  return Promise.reject(-100)
          	},
          	(reason) => {
          		console.log("p失败了1", reason)
          	}
          // 3. 执行Promise实例1.then()，返回一个Promise实例，没有接收，称为Promise实例2。指定好了Promise实例1成功和失败状态的回调函数，但目前还未执行
          ).then(
          	(value) => {
          		console.log("p成功了2", value)
                  return true
          	},
          	(reason) => {
          		console.log("p失败了2", reason)
                  return 100
          	}
          // 4. 执行Promise实例2.then()，返回一个Promise实例，没有接收，称为Promise实例3。指定好了Promise实例2成功和失败状态的回调函数，但目前还未执行
          ).then(
          	(value) => {
          		console.log("p成功了3", value)
                  return false
          	},
          	(reason) => {
          		console.log("p失败了3", reason)
                  return false
          	}
          // 5. 执行Promise实例3.then()，返回一个Promise实例，没有接收，称为Promise实例4。指定好了Promise实例3成功和失败状态的回调函数，但目前还未执行
          ).then(
          	(value) => {
          		console.log("p成功了4", value)
                  return -100
          	},
          	(reason) => {
          		console.log("p失败了4", reason)
          	}
          )
          
          // 6. 同步代码执行完毕后，执行异步队列里的任务，定时器的异步回调，
          	//4.1 改变了实例p的状态为失败，且value为'a'。然后将实例p的成功回调函数压入异步队列中。
          	//4.2 接着执行console.log(1)，打印出1(得先把当前任务执行完毕，再去考虑其他任务)
          
          // 5. 执行完毕后，从异步队列里拿出任务，实例p的成功回调函数
          	//5.1 执行console.log("p成功了1", value)，打印 "p成功了1"a
          	//5.2 返回的是一个失败状态的Promise对象，且reason为-100。所以Promise实例1的状态也变为失败的，且reason为-100。将Promise实例1的失败状态对应的回调函数压入异步队列中。
          
          // 6. 执行完毕后，从异步队列里拿出任务，Promise实例1的失败回调函数
          	// 6.1 执行console.log("p失败了2", reason); 打印 "p失败了2"-100
          	// 6.2 返回的是一个非Promise值100。所以Promise实例2的状态也变为成功的，且value为100。将Promise实例2的成功状态对应的回调函数压入异步队列中。
          
          // 7. 执行完毕后，从异步队列里拿出任务，Promise实例2的成功回调函数
          	// 7.1 执行console.log("p成功了3", value)); 打印 "p成功了3"100
          	// 7.2 返回的是一个非Promise值false。所以Promise实例3的状态也变为成功的，且value为false。将Promise实例3的成功状态对应的回调函数压入异步队列中。
          
          // 8. 执行完毕后，从异步队列里拿出任务，Promise实例3的成功回调函数
          	// 8.1 执行console.log("p成功了4", value); 打印 "p成功了4"false
          	// 8.2 返回的是一个非Promise值-100。所以Promise实例4的状态也变为成功的，且value为-100。未指定Promise实例4的回调函数
          
          
          //最终输出为 
          // 1
          // "p成功了1"a
          // "p失败了2"-100
          // "p成功了3"100
          // "p成功了4"false
          ```
      
        - ![image-20220808162238537](C:\Users\zayn\AppData\Roaming\Typora\typora-user-images\image-20220808162238537.png)
   3. 如果`then`所指定的==回调抛出异常==
      - 那么==【新的`Promise`实例】==状态：失败(rejected)，reason为抛出的那个异常
      
        - 示例一
      
          - ``` js
            // 1. 执行new Promise(executor)，返回一个Promise实例对象，用变量p接收。executor是同步回调函数，会立马执行 
            const p = new Promise((resolve, reject) => {
                // 1.1 执行setTimeout()，开启定时器，1s钟后将异步回调函数压入异步队列
            	setTimeout(()=>{
            		resolve('a')
                    console.log(1)
                }, 1000)
            });
            
            // 2. 执行p.then()，返回一个Promise实例，没有接收，称为Promise实例1。指定好了p实例成功和失败状态的回调函数，但目前还未执行
            p.then(
            	(value) => {
            		console.log("p成功了1", value)
                    return Promise.reject(-100)
            	},
            	(reason) => {
            		console.log("p失败了1", reason)
            	}
            // 3. 执行Promise实例1.then()，返回一个Promise实例，没有接收，称为Promise实例2。指定好了Promise实例1成功和失败状态的回调函数，但目前还未执行
            ).then(
            	(value) => {
            		console.log("p成功了2", value)
                    return true
            	},
            	(reason) => {
            		console.log("p失败了2", reason)
                    return 100
            	}
            // 4. 执行Promise实例2.then()，返回一个Promise实例，没有接收，称为Promise实例3。指定好了Promise实例2成功和失败状态的回调函数，但目前还未执行
            ).then(
            	(value) => {
            		console.log("p成功了3", value)
                    throw 900
            	},
            	(reason) => {
            		console.log("p失败了3", reason)
                    return false
            	}
            // 5. 执行Promise实例3.then()，返回一个Promise实例，没有接收，称为Promise实例4。指定好了Promise实例3成功和失败状态的回调函数，但目前还未执行
            ).then(
            	(value) => {
            		console.log("p成功了4", value)
                    return -100
            	},
            	(reason) => {
            		console.log("p失败了4", reason)
            	}
            )
            
            // 6. 同步代码执行完毕后，执行异步队列里的任务，定时器的异步回调，
            	//4.1 改变了实例p的状态为失败，且value为'a'。然后将实例p的成功回调函数压入异步队列中。
            	//4.2 接着执行console.log(1)，打印出1(得先把当前任务执行完毕，再去考虑其他任务)
            
            // 5. 执行完毕后，从异步队列里拿出任务，实例p的成功回调函数
            	//5.1 执行console.log("p成功了1", value)，打印 "p成功了1"a
            	//5.2 返回的是一个失败状态的Promise对象，且reason为-100。所以Promise实例1的状态也变为失败的，且reason为-100。将Promise实例1的失败状态对应的回调函数压入异步队列中。
            
            // 6. 执行完毕后，从异步队列里拿出任务，Promise实例1的失败回调函数
            	// 6.1 执行console.log("p失败了2", reason); 打印 "p失败了2"-100
            	// 6.2 返回的是一个非Promise值100。所以Promise实例2的状态也变为成功的，且value为100。将Promise实例2的成功状态对应的回调函数压入异步队列中。
            
            // 7. 执行完毕后，从异步队列里拿出任务，Promise实例2的成功回调函数
            	// 7.1 执行console.log("p成功了3", value)); 打印 "p成功了3"100
            	// 7.2 抛出异常，实例3的状态变为fulfilled，且reason为异常值900。将Promise实例3的失败状态对应的回调函数压入异步队列中。
            
            // 8. 执行完毕后，从异步队列里拿出任务，Promise实例3的失败回调函数
            	// 8.1 执行console.log("p失败了4", value); 打印 "p失败了4"900
            	// 8.2 返回的是一个非Promise值undefined。所以Promise实例4的状态也变为成功的，且value为-100。未指定Promise实例4的回调函数
            
            
            //最终输出为 
            // 1
            // "p成功了1"a
            // "p失败了2"-100
            // "p成功了3"100
            // "p失败了4"900
            ```
      
          - ![image-20220808162704637](C:\Users\zayn\AppData\Roaming\Typora\typora-user-images\image-20220808162704637.png)

## 4、==利用链式调用解决回调地狱==

### 4.1 纯回调函数发送请求造成的回调地狱

- 要求：在第一次请求发送成功并收到响应后发送第二次请求，在第二次请求发送成功并收到响应后发送第三次请求

- ``` js
        sendAjax(
          "http://localhost:3000/users/get_req",
          { name: "Ash", age: 26 },
          (response) => {
            console.log("第一次请求成功", response);
            sendAjax(
              "http://localhost:3000/users/get_req",
              { name: "V", age: 26 },
              (response) => {
                console.log("第二次请求成功", response);
                sendAjax(
                  "http://localhost:3000/users/get_req",
                  { name: "Ash", age: 26 },
                  (response) => {
                    console.log("第三次请求成功", response);
                  },
                  (error) => {
                    console.log("第三次请求失败", error);
                  }
                );
              },
              (error) => {
                console.log("第二次请求失败", error);
              }
            );
          },
          (error) => {
            console.log("第一次请求失败", error);
          }
        );
  ```

- 

### 4.2 利用Promise的链式调用特性解决回调地狱

#### 4.2.1 一开始自己的想法

``` js
// 1. 首先发送第一个请求。当第一个请求成功时再发送第二个请求。而如何要得知第一个请求是否发送成功呢，就需要.then指定成功和失败状态的回调，看最终被调用的是哪个。
sendAjax('http://localhost:3000/users/get_req', {name: 'Ash'})
    .then(
    (value) => {
        console.log('第一个请求发送成功了', value)
    	//2. 第一个请求发送成功了，在这里发送第二个请求。而如何要得知第二个请求是否发送成功呢，就需要.then指定成功和失败状态的回调，看最终被调用的是哪个。在这里发现了不对劲，好像又陷入了回调地狱，在不断地嵌套中。
        sendAjax('http://localhost:3000/users/get_req', {name: 'Ash'})
        	.then()
    }
	(error) => {console.log('第一个请求发送失败了', error)})
```

#### 4.2.2 解决思路

- 关键点：==`.then`返回的新Promise实例，其状态和值由`then()`所指定的回调函数执行的结果决定== 。当回调函数执行后返回的是Promise实例时，==`.then`返回的新Promise实例的状态和值与回调函数执行后返回的Promise实例一样==。因此如果我们`return sendAjax('http://localhost:3000/users/get_req', {name: 'Ash'})`，那么我们就可以通过==`.then`返回的新实例的状态来知道用于发送请求的`sendAjax('http://localhost:3000/users/get_req', {name: 'Ash'})`实例的状态，就可以知道请求是否发送成功==

``` js
// 1. 首先发送第一个请求。当第一个请求成功时再发送第二个请求。而如何要得知第一个请求是否发送成功呢，就需要.then指定成功和失败状态的回调，看最终被调用的是哪个。
sendAjax('http://localhost:3000/users/get_req', {name: 'Ash'})
	.then( //a
    (value)=>{
        console.log('第一个请求发送成功')
        // 2. 第一个请求发送成功后，发送第二个请求, 此时我们return这个promise对象。这样可以使得a处的.then返回的新Promise实例（称为新Promise实例1）它的状态就是用于发送第二个请求的实例的状态，所以想知道第二个请求是否发送成功，就是看新Promise实例1的状态是否是成功，而如何得知新Promise实例1的状态是否成功，就再次在外面用.then
        return sendAjax('http://localhost:3000/users/get_req', {name: 'Ash'})
    })
	.then( //b
    (value)=>{
        console.log('第二个请求发送成功')
        // 3. 第二个请求发送成功后，发送第三个请求, 此时我们return这个promise对象。这样可以使得b处的.then返回的新Promise实例（称为新Promise实例2）它的状态就是用于发送第三个请求的实例的状态，所以想知道第三个请求是否发送成功，就是看新Promise实例2的状态是否是成功，而如何得知新Promise实例2的状态是否成功，就再次在外面用.then
        return sendAjax('http://localhost:3000/users/get_req', {name: 'Ash'})
    })
	.then( //c
    (value)=>{
        console.log('第三个请求发送成功')
        // 4. 第三个请求发送成功后，发送第四个请求, 此时我们return这个promise对象。这样可以使得c处的.then返回的新Promise实例（称为新Promise实例3）它的状态就是用于发送第四个请求的实例的状态，所以想知道第四个请求是否发送成功，就是看新Promise实例3的状态是否是成功，而如何得知新Promise实例3的状态是否成功，就再次在外面用.then
        return sendAjax('http://localhost:3000/users/get_req', {name: 'Ash'})
    })
```

